functional:
- Пользователь должен иметь возможность фильтровать товары 
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре 
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен иметь мобильную версию
- Сайт должен быть доступен на различных устройствах
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть безопасным и защищать данные пользователя
implicit:
- Должна быть английская и русская версии сайта
- Кнопка "очистить корзину" должна быть красная, а "оформить заказ" зеленая
- Пользователь не должен иметь возможность редактировать данные о товаре (цену, описание, фото)
- На этапе оформления заказа у посетителя необходимо запросить контактные данные
